---
title: "Hannah Pryor"
format: html
editor: visual
---

<br>

> | Ithaca, NY, USA  
> | hgp26\@cornell.edu  
> | (419) 610-8837  
> | [LinkedIn](https://www.linkedin.com/in/hannah-pryor-792004337/)

<br>

#### CAREER OBJECTIVES

*Research and education in ornithology and evolutionary biology*

My primary areas of interest are hybridization, speciation, and bioacoustics. I am particularly curious about the role of song and song learning in passerine hybrid zones, and how this can facilitate or inhibit the speciation process.

<br>

#### EDUCATION

Cornell University, Ithaca, New York — B.S., Environment and Sustainability, May 2026

<br>

#### RESEARCH EXPERIENCE

<br>

-   YELLOW-RUMPED WARBLER SONG PLAYBACK RESEARCH — *February 2023-present*

    *Independent undergraduate research project supervised by Dr. Irby Lovette looking at song recognition and speciation in the eastern and western subspecies of the Yellow-rumped Warbler*

    -   Independent field work in California, Northeast U.S., Washington, and Alberta conducting song playback trials

    -   Tent camping in a variety of conditions and strenuous hiking at high elevations 

    -   Targeted sound recording for Macaulay Library

    -   R programming

<br>

-   FAIRYWREN BANDING ASSISTANT — Lake Samsonvale, Queensland, Australia — *July-August 2024*

    *The Fairywren Project — long term study of various aspects of fairywren biology across Australia*

    -   Setting up, taking down, and storing mist nets

    -   Banding and processing a variety of different local bird species

    -   Color banding (plastic bands, solder closed) of three fairywren species

    -   Digital and physical recording of banding data in the field

<br>

-   FAIRYWREN LAB ASSISTANT — Cornell Lab of Ornithology — *March-May 2024*

    *Research looking at telomere length in Variegated Fairywrens from northern Australia*

    -   DNA extraction from blood samples in lysis buffer

    -   Qubit and Quikdrop to measure DNA concentrations

    -   LabArchives and Excel

    -   Ongoing genomic analysis with possible F1 and F2 hybrid Red-Backed x Superb Fairywren DNA

<br>

-   HUBBARD BROOK FIELD ORNITHOLOGY PROGRAM: BLACK-THROATED BLUE WARBLER CREW — Hubbard Brook Experimental Forest, NH — *Summer 2023*

    *Long-term research on Black-throated Blue Warblers and how they respond to environmental changes*

    -   Nest searching and monitoring

    -   Territory mapping

    -   Nestling banding, brachial bleeding, and processing

    -   Predator counts and food abundance surveys

<br>

-   FLORIDA SCRUB-JAY LAB ASSISTANT — Cornell Lab of Ornithology — *September 2022-May 2023*

    *Long-term research on ecology of Florida Scrub-Jays in Florida’s unique oak scrub habitat*

    -   DNA extraction blood samples in lysis buffer

    -   PCR and gel electrophoresis for molecular sexing

    -   LabArchives and Excel

    -   Traveled to Archbold Biological Station for spring break to help with field work for the project

<br>

#### RELEVANT COURSEWORK

<br>

OTS TROPICAL BIOLOGY ON A CHANGING PLANET — STUDY ABROAD IN COSTA RICA — *Spring 2025*

NTRES 3150/3151 — CONSERVATION BIOACOUSTICS — FIELD COURSE IN HAWAII — *Fall 2024-Winter 2025*

BIOEE 2525/2526/2527 — ECOLOGY AND CONSERVATION OF WILDLIFE IN THE NEOTROPICS — FIELD COURSE IN PATAGONIA, ARGENTINA — *Fall 2023-Spring 2024*

BIOEE 4940 — ADVANCED ORNITHOLOGICAL ILLUSTRATION — *Fall 2023*

BIOEE 2150 — TECHNIQUES IN AVIAN SPECIMEN PREPARATION — *Fall 2022*

<br>

#### PRESENTATIONS

<br>

**Pryor, H.**, S.A. Kaiser, and I. Lovette. Reciprocal song playback and subspecies recognition in the yellow-rumped warbler complex. American Ornithological Society Annual Meeting, Estes Park, CO, October 2024 \[Poster\]

**Pryor, H.**, I. Lovette, and S.A. Kaiser. Geographic song variation and subspecies recognition in the yellow-rumped warbler complex. Hubbard Brook Ecosystem Study 60th Annual Cooperators’ Meeting, Plymouth, NH, July 2023 \[Lightning Talk\]

<br>

#### AWARDS AND GRANTS

<br>

-   RESEARCH GRANTS — \$6792

    -   *Association of Field Ornithologists - Bergstrom Grant*, Spring 2025 — \$1000

    -   *Undergraduate Research Fund at the Cornell Lab of Ornithology*, Spring 2025 — \$2000

    -   *Cornell University College of Agriculture and Life Sciences Alumni Association Grant*, Spring 2025— \$1000

    -   *Undergraduate Research Fund at the Cornell Lab of Ornithology*, Spring 2024 — \$792

    -   *Cornell University College of Agriculture and Life Sciences Undergraduate Research Grant*, Fall 2023 — \$2000

<br>

-   OTHER AWARDS AND FUNDING

    -   *Cornell University College of Agriculture and Life Sciences Alumni Association Grant* \[travel grant\], Fall 2023 — \$250 

    -   *Knight Prize for Writing in the Majors* \[honorable mention\], April 2023 — \$100 award

<br>

#### WORK EXPERIENCE

<br>

-   PE INSTRUCTOR - Cornell Outdoor Education — *April 2023-present*

    -   Organizing and co-instructing backpacking, rock climbing, canoeing, and stand-up paddleboarding courses

<br>

-   SNOW SPORTS INSTRUCTOR - Snow Trails Ski Resort, Mansfield, Ohio — *November 2019-present*

    -   Teaching group and private downhill ski lessons across a variety of ages and ability levels

<br>

-   ENVIRONMENTAL EDUCATION INTERN - Gorman Nature Center, Lexington, Ohio — *Summer 2022*

    -   Organization and execution of environmental outreach events, including bird walks and a summer day camp for kids

    -   Land management tasks, including trail maintenance, nest box monitoring, and invasive species removal

<br>

#### LEADERSHIP EXPERIENCE

<br>

BIRDING CLUB AT CORNELL EXECUTIVE BOARD: TRIP CHAIR — 2024

CORNELL BIOACOUSTICS CLUB EXECUTIVE BOARD: OUTREACH CHAIR — 2025

<br>

#### PROFESSIONAL SKILLS AND EXPERIENCE

<br>

GENERAL SKILLS

-   Advanced knowledge of avian anatomy, ecology, and evolution from challenging coursework and educational experiences

-   Spanish language \[conversational\]

<br>

FIELD SKILLS

-   Bird identification by sight and sound

-   Long-term monitoring: nest searching, territory mapping, predator and insect/arachnid abundance surveys

-   Banding: aluminum and color bands, adult and nestling birds, processing and scribing, nestling brachial bleeding

-   Targeted sound recording, passive acoustic monitoring, playback experiments

-   Intense hiking and camping for field work in a variety of conditions and locations

<br>

LAB SKILLS

-   DNA extraction, PCR, and gel electrophoresis

-   Qubit and Quikdrop

<br>

SOFTWARE SKILLS

-   R programming:

    -   Data visualization

    -   T-test, chi-squared test of association, ANOVA/Kruskal-Wallis tests

    -   Principal Component Analysis

    -   Linear modeling

-   Bioacoustics software: Raven Pro, Raven Compass, Raven Expedition, BirdNET

-   QGIS software

<br>
